=encoding utf-8


=head1 Changelog


All notable changes to C<lua-resty-session> will be documented in this file.


=head2 [2.25] - 2019-11-06


=head3 Added


=over


=item *

Add SSL support for the Redis storage option (#75) (thanks @tieske)

=item *

DSHM storage adapter (a distributed SHM storage based on Hazelcast for Nginx) (thanks @grrolland)


=back


=head2 [2.24] - 2019-07-09


=head3 Fixed


=over


=item *

Avoid use unix socket and redis password with empty string

=item *

Provide session id when closing, otherwise the lock is not deleted


=back


=head3 Added


=over


=item *

Added a configuration for session cookie max size (C<session.cookie.maxsize>)


=back


=head2 [2.23] - 2018-12-12


=head3 Added


=over


=item *

Added pluggable strategies with C<default> and a new C<regenerate> strategy

=item *

Added pluggable C<hmac>s

=item *

Added C<session.close>

=item *

Added C<ttl> to C<storages>

=item *

Added C<session.cookie.discard>, a C<ttl> how long to keep old sessions when
renewing (used by C<regenerate> strategy


=back


=head2 [2.22] - 2018-03-17


=head3 Fixed


=over


=item *

Only sets self.cookie.secure if not defined.


=back


=head2 [2.21] - 2018-03-16


=head3 Screwed


=over


=item *

Forgot to bump version number.


=back


=head2 [2.20] - 2018-03-16


=head3 Fixed


=over


=item *

Fixes issue where check addr and check scheme could be faked.
See also: https://github.com/bungle/lua-resty-session/issues/47
Thanks @nielsole


=back


=head2 [2.19] - 2017-09-19


=head3 Fixed


=over


=item *

Fixes small bug where aes could generate invalid salt on invalid input
that further crashes Lua with error: bad argument #2 to 'salt' (number
expected, got no value)


=back


=head2 [2.18] - 2017-07-10


=head3 Fixed


=over


=item *

Automatically creates exactly 64 bits salt as required by the latest
lua-resty-string.
See also: https://github.com/bungle/lua-resty-session/issues/40
Thanks @peturorri


=back


=head2 [2.17] - 2017-06-12


=head3 Added


=over


=item *

Added session.hide() function to hide session cookies from upstream
on reverse proxy scenarios.


=back


=head2 [2.16] - 2017-05-31


=head3 Changed


=over


=item *

Delays setting the defaults until needed, allowing users to safely
require "resty.session" in different contexts.


=back


=head2 [2.15] - 2017-02-13


=head2 Added


=over


=item *

Added a support for chunked cookies.
See also: https://github.com/bungle/lua-resty-session/issues/35
Thanks @zandbelt


=back


=head2 [2.14] - 2016-12-16


=head3 Fixed


=over


=item *

Lua code configuration parsing corrections (especially on boolean
options).


=back


=head2 Added


=over


=item *

Added a more natural way to pass config arguments to storage
adapters and ciphers in Lua code.
See also: https://github.com/bungle/lua-resty-session/issues/34
Thanks @hanxi


=back


=head2 [2.13] - 2016-11-21


=head3 Changed


=over


=item *

On start we do send cookie now also if the settings have changed
and the cookie expiry time needs to be reduced.


=back


=head3 Fixed


=over


=item *

Memcache storage adapter had a missing ngx.null.


=back


=head2 [2.12] - 2016-11-21


=head3 Added


=over


=item *

Implemented pluggable session identifier generators.

=item *

Implemented random session idenfier generator.


=back


=head3 Changed


=over


=item *

Now checks if headers were already sent before trying to set the
cookie headers.

=item *

SSL session identifier is not checked by default anymore.

=item *

Lua session.identifier.length changed to session.random.length.

=item *

Nginx $session_identifier_length changed to $session_random_length.


=back


=head2 [2.11] - 2016-09-30


=head3 Changed


=over


=item *

Just another OPM release to correct the name.


=back


=head2 [2.10] - 2016-09-29


=head3 Added


=over


=item *

Support for the official OpenResty package manager (opm).


=back


=head3 Changed


=over


=item *

Changed the change log format to keep-a-changelog.


=back


=head2 [2.9] - 2016-09-01


=head3 Fixed


=over


=item *

Bugfix: Weird bug where RAND_bytes was not working on Windows platform.
Code changed to use resty.random. See Also:
https://github.com/bungle/lua-resty-session/issues/31
Thanks @gtuxyco


=back


=head2 [2.8] - 2016-07-05


=head3 Fixed


=over


=item *

Bugfix: AES Cipher used a wrong table for cipher sizes.
See Also: https://github.com/bungle/lua-resty-session/issues/30
Thanks @pronan


=back


=head2 [2.7] - 2016-05-18


=head3 Added


=over


=item *

Redis storage adapter now supports Redis authentication.
See Also: https://github.com/bungle/lua-resty-session/pull/28
Thanks @cheng5533062


=back


=head2 [2.6] - 2016-04-18


=head3 Changed


=over


=item *

Just cleanups and changed _VERSION to point correct version.


=back


=head2 [2.5] - 2016-04-18


=head3 Fixed


=over


=item *

session.save close argument was not defaulting to true.


=back


=head2 [2.4] - 2016-04-17


=head3 Added


=over


=item *

Cookie will now have SameSite attribute set as "Lax" by default.
You can turn it off or set to "Strict" by configuration.


=back


=head3 Changed


=over


=item *

Calling save will now also set session.id if the save was called
without calling start first.
See Also: https://github.com/bungle/lua-resty-session/issues/27
Thanks @hcaihao


=back


=head2 [2.3] - 2015-10-16


=head3 Fixed


=over


=item *

Fixes issue #19 where regenerating session would throw an error
when using cookie storage.
See Also: https://github.com/bungle/lua-resty-session/issues/19
Thanks @hulu1522


=back


=head2 [2.2] - 2015-09-17


=head3 Changed


=over


=item *

Removed all session_cipher_* deprecated settings (it was somewhat
broken in 2.1).

=item *

Changed session secret to be by default 32 bytes random data
See Also: https://github.com/bungle/lua-resty-session/issues/18
Thanks @iain-buclaw-sociomantic


=back


=head3 Added


=over


=item *

Added documentation about removed features and corrected about
session secret size accordingly.


=back


=head2 [2.1] - 2015-09-07


=head3 Added


=over


=item *

Added architecture for Cipher adapter plugins.
See Also: https://github.com/bungle/lua-resty-session/issues/16
Thanks @mingfang

=item *

Implemented AES cipher adapter (just like it was before)

=item *

Implemented None cipher adapter (no encryption)

=item *

Added documentation about pluggable ciphers


=back


=head3 Changed


=over


=item *

Changed JSON serializer to use cjson.safe instead


=back


=head2 [2.0] - 2015-08-31


=head3 Added


=over


=item *

Added architecture for Storage adapter plugins.
See Also: https://github.com/bungle/lua-resty-session/issues/13

=item *

Implemented Client Side Cookie storage adapter.

=item *

Implemented Memcache storage adapter.
See Also: https://github.com/bungle/lua-resty-session/pull/14
Thanks @zandbelt

=item *

Implemented Redis storage adapter.

=item *

Implemented Shared Dictionary (shm) storage adapter.

=item *

Added architecture for Encoder and Decoder plugins.

=item *

Implemented Base 64 encoder / decoder.

=item *

Implemented Base 16 (hex) encoder / decoder.

=item *

Added architecture for Serializer plugins

=item *

Implemented JSON serializer.

=item *

Persistent cookies will now also contain Max-Age in addition to Expires.

=item *

Cookie domain attribute is not set anymore if not specified.

=item *

Added notes about using lua-resty-session with Lua code cache turned off.
See also: https://github.com/bungle/lua-resty-session/issues/15
Thanks @BizShuk


=back


=head2 [1.7] - 2015-08-03


=head3 Added


=over


=item *

Added session.open() function that only opens a session but doesn't send
the cookie (until start is called).
See also: https://github.com/bungle/lua-resty-session/issues/12
Thanks @junhanamaki


=back


=head3 Fixed


=over


=item *

Fixed cookie expiration time format on Firefox bug:
https://github.com/bungle/lua-resty-session/pull/10
Thanks @junhanamaki

=item *

Bugfix: Fixed an issue of overwriting a variable:
https://github.com/bungle/lua-resty-session/pull/11
Thanks @junhanamaki


=back


=head2 [1.6] - 2015-05-05


=head3 Fixed


=over


=item *

Fixed truncated cookie value bug:
https://github.com/bungle/lua-resty-session/pull/8
Thanks @kipras


=back


=head2 [1.5] - 2014-11-27


=head3 Fixed


=over


=item *

Cookies are not always "secure":
https://github.com/bungle/lua-resty-session/issues/5
Thanks @vladimir-smirnov-sociomantic


=back


=head3 Added


=over


=item *

Added documentation about Nginx SSL/TLS configuration settings related
to session lifetime and ssl session ids.


=back


=head2 [1.4] - 2014-11-26


=head3 Fixed


=over


=item *

Bugfix: Fixed an issue where session configurations did get cached
on a module level. This issue is discussed in pull-request #4:
https://github.com/bungle/lua-resty-session/pull/4
Thanks @kipras.


=back


=head3 Added


=over


=item *

Added session.new function.

=item *

Added documentation about Nginx configuration used as defaults (not read
on every request), and documented session.new.


=back


=head3 Changed


=over


=item *

session.start{ ... } (a call with config parameters) works now as expected.

=item *

session.start now returns additional extra boolean parameter that can be
used to check if the session is s new session (false) or a previously
started one (true).


=back


=head2 [1.3] - 2014-11-14


=head3 Added


=over


=item *

Added support for persistent sessions. See issue #2.

=item *

Added session.check.ssi, session.cookie.persistent and the related Nginx
configuration variables.

=item *

Added Max-Age=0 to expiration code.


=back


=head2 [1.2] - 2014-10-12


=head3 Fixed


=over


=item *

Changed encode and decode functions to operate with correct number of
arguments. See issue #1.


=back


=head2 [1.1] - 2014-10-03


=head3 Security


=over


=item *

There was a bug where additional user agent, scheme, and remote addr
(disabled by default) was not checked.


=back


=head3 Added


=over


=item *

Added _VERSION field.


=back


=head3 Changed


=over


=item *

Simplied a code a lot (e.g. internal setcookie and getcookie functions are
now cleaner). Removed a lot of unneccessary lines from session.start by
adding configs directly to session prototype.


=back


=head2 [1.0] - 2014-09-24


=head3 Added


=over


=item *

LuaRocks Support via MoonRocks.

=back

